In [1]:
import time
import json
import copy
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from PIL import Image
from collections import OrderedDict
import torch
from torch import nn, optim
from torch.optim import lr_scheduler
from torch.autograd import Variable
from torchvision import datasets, models, transforms

In [2]:
device = torch.device('cpu')

In [36]:
model = models.vgg19()

In [38]:
classifier = nn.Sequential(OrderedDict([
                          ('fc1', nn.Linear(25088, 4096)),
                          ('relu', nn.ReLU()),
                          ('fc2', nn.Linear(4096, 102)),
                          ('output', nn.LogSoftmax(dim=1))
                          ]))

In [39]:
model.classifier = classifier

In [40]:
model.load_state_dict(torch.load('/Users/morgan2448/Downloads/themodel.pth', map_location=device))

<All keys matched successfully>

In [41]:
data_transforms = {
    'validset': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], 
                             [0.229, 0.224, 0.225])
    ]),
}

In [46]:
def calc_accuracy(model, dataloaders, data, cuda=False):
    model.eval()
    material = []
    with torch.no_grad():
        for idx, (inputs, labels) in enumerate(dataloaders[data]):
            if cuda:
                inputs, labels = inputs, labels
            # obtain the outputs from the model
            outputs = model.forward(inputs)
            # max provides the (maximum probability, max value)
            _, predicted = outputs.max(dim=1)
            material.append(predicted)
            # check the 
            if idx == 0:
                print(predicted) #the predicted class
                print(torch.exp(_)) # the predicted probability
            equals = predicted == labels.data
            if idx == 0:
                print(equals)
            print(equals.float().mean())
    return material

In [47]:
def image_predictor(path,ground_truth=0):
    image = Image.open(path)
    imagetensor = data_transforms['validset'](image)
    dataset_single = torch.utils.data.TensorDataset(imagetensor[None], torch.tensor([ground_truth]))
    dataloader_valid_single = torch.utils.data.DataLoader(dataset_single, batch_size=1, shuffle = False)
    dataloader = {
        'train' : dataloader_valid_single,
        'valid' : dataloader_valid_single
    }
    value2 = calc_accuracy(model,dataloader,'valid',True)[0].item()
    return SingleNumToMaterial(value2)

In [48]:
def SingleNumToMaterial(value):
    if torch.tensor(value).item() == 0:
        return('cardboard')
    elif torch.tensor(value).item() == 1:
        return('glass')
    elif torch.tensor(value).item() == 2:
        return('metal')
    elif torch.tensor(value).item() == 3:
        return('paper')
    elif torch.tensor(value).item() == 4:
        return('plastic')

In [56]:
image_predictor('/Users/morgan2448/Downloads/phonecloseup.jpg')

tensor([1])
tensor([0.7995])
tensor([False])
tensor(0.)


'glass'

In [52]:
aa

'glass'